production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    include_root_in_json: true
    raise_not_found_error: false
development:
  sessions:
    default:
      database: gameroom_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: gameroom_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
