# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8677d1bc672018ca98f5c8663790d2ca39aa2e17ae029e9142e0a00ddf75678ad2f7a89bab27356df154653a2096e64ea49477a3732dc24a0bcc1f2a244280b2

test:
  secret_key_base: bc915e3f1bbf79971b9a2d90891acdfc3cfa5eb2e533d9f263862f0b774834acfa2a0b8355d931f40e321452c49d3aca26d7b42ae06354e79fed3ce09a31ca20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
